# Generated by Django 3.2.2 on 2021-06-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='post',
            name='description_uz',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
