# Generated by Django 3.2.2 on 2021-06-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210615_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='comment',
            new_name='comment_en',
        ),
        migrations.AddField(
            model_name='followers',
            name='comment_uz',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
